### PR TITLE
feat(doc): adding documentation for the `exit` builtin function

### PR DESCRIPTION
**Pull request by MuhamedMagdi**
Adding the documentation for the new `exit` builtin function

### CODE REVIEW

**Review by Ph0enixKM — APPROVED** [review]
LGTM

**Comment by Mte90** [comment]
I think that it is the case to merge when the new amber version is released officially.

**Review by Ph0enixKM — APPROVED** [review]
Thank you for this contribution! 👏

**Comment by Ph0enixKM** [comment]
Oh hang on. I thought we already support exit, but we're still waiting for https://github.com/amber-lang/amber/pull/566 to get merged. Merge is coming pretty soon

**Comment by Ph0enixKM** [comment]
@Mte90 merging this one before my big change will be easier to resolve (I only moved the files in my change so git knows that it needs to update them in the other directory). I advise to merge them both at the same time - this one first.

**Review by Mte90 — APPROVED** [review]

**Comment by Mte90** [comment]
ready for you

**Pull request merged**
